# Generated by Django 5.2.5 on 2025-08-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=50),
        ),
    ]
